// Auto-generated by vite-plugin-test, do not edit manually

export * as './src/simple.test' from './src/simple.test'
export * as './src/sample.test' from './src/sample.test'
export * as './src/components/components.test' from './src/components/components.test'
export * as './src/components/another-components.test' from './src/components/another-components.test'