/**
 * @file This file serves as the main entry point for the `matcher` directory,
 * re-exporting all individual matcher implementations.
 * These matchers extend the `Expect` prototype, providing a rich set of assertion capabilities
 * for the `@woby/chk` testing framework.
 */

export * from './not'
export * from './deep.equals'
export * from './equals'
export * from './not.deep.equals'
export * from './not.equals'
export * from './title'
export * from './array.contains'
export * from './resolves'
export * from './rejects'
export * from './toThrow'
export * from './toThrowErrorContains'
export * from './toHaveBeenCalled'
export * from './toHaveBeenCalledTimes'
export * from './toHaveBeenCalledWith'
export * from './toHaveBeenCalledLastCalledWith'
export * from './toHaveBeenCalledNthCalledWith'
export * from './toHaveReturnedTimes'
export * from './toHaveReturnedWith'
export * from './toHaveLastReturnedWith'
export * from './toHaveNthReturnedWith'
export * from './toHaveReturned'
export * from './numericComparisons'
export * from './toHaveLength'
export * from './toHaveProperty'
export * from './toBeCloseTo'
export * from './toBeDefined'
export * from './toBeFalsy'
export * from './toBeInstanceOf'
export * from './toBeNull'
export * from './toBeUndefined'
export * from './toBeNaN'
export * from './toContain'
export * from './toContainEqual'
export * from './toEqual'
export * from './toMatch'
export * from './toMatchObject'
export * from './toStrictEqual'
export * from './toBeTruthy'
export * from './toBeOneOf'
export * from './toBeTypeOf'
export * from './toHaveResolved'
export * from './toHaveResolvedTimes'
export * from './toHaveResolvedWith'
export * from './toHaveLastResolvedWith'
export * from './toHaveNthResolvedWith'
export * from './toSatisfy'
export * from './htmlToMatchSnapshot'